config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'static_pages/about'
  get 'signup' => 'users#new'
  resources :users
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  #Is given by Rails
  #attr_accessor :password, password_confirmation
  before_save {self.email = email.downcase}
  validates :name,  presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 50},
  format: {with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
      flash[:success] = "Successful Signup"
    else
      render 'new'
    end
  end

  private 
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title= '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #returns gravitar
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = 'https://secure.gravatar.com/avatar/#{gravatar_id}'
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <h3>Footer</h3>
</div>

app/views/layouts/_navigations.html.erb
<div class="navigation">
    <ul><%= link_to "Home", root_path%></ul>
    <ul><%= link_to "About", static_pages_about_path%></ul>
    <ul><%= link_to "Contact", contact_path%></ul>
    <ul><%= link_to "Help", help_path%></ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigations' %>
  <% flash.each do |message_type, message|%>
    <%= message %>
  <% end %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      This form contains <%= pluralize(@user.errors.count, "error") %> 
    </div>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>   
<h1>ABOUT</h1>
<p>
  This is the home page for the
  <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>   

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
This is the help page
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>HOME APP</h1>
<p>
  It's home
</p>

<%= link_to "Sign Up", signup_path, class:"btn"%>

app/views/users/index.html.erb
<h1>Users Go Here</h1>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>
<div class="row">
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
<br>
  <%= f.submit "Create Account", class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%# <%= render 'shared/success_message' %> %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>